---
name: Build docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - development
    paths:
      - 'Dockerfile'
      - 'src/**'
      - 'workflows/build-docker.yml'
      - 'Cargo.toml'
      - 'Cargo.lock'

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write

env:
  APPLICATION_NAME: cert-manager-plesk-webhook
  DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/cert-manager-plesk-webhook

jobs:
  build_docker_image:
    name: Build docker image
    environment: ${{ github.ref_name}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          load: true
          file: Dockerfile
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ vars.DOCKER_IMAGE_VERSION }}

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.DOCKER_IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.APPLICATION_NAME}}:latest