name: Application release

permissions:
  id-token: write
  attestations: write
  packages: write
  contents: write

on:
  push:
    tags:
      - v*

env:
  APPLICATION_NAME: cert-manager-plesk-webhook
  DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/cert-manager-plesk-webhook

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update rust toolchain
        run: |
          rustup update

      - name: Build
        run: |
          cargo build --release

      - name: Generate Checksums
        run: |
          sha256sum target/release/${{ env.APPLICATION_NAME}} > sha256sum.txt
          md5sum target/release/${{ env.APPLICATION_NAME}} > md5sum.txt

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: target/release/${{ env.APPLICATION_NAME}}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        id: push
        uses: docker/build-push-action@v3
        with:
          push: true
          load: true
          file: Dockerfile
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.DOCKER_IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$GITHUB_REF_NAME" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REF_NAME}" \
            --generate-notes \
            --verify-tag \
            --notes "Docker Image:\n\n\`\`\`\nDocker pull ${{ env.APPLICATION_NAME }}:${{ github.ref_name }}\nDocker pull ${{ env.APPLICATION_NAME }}:latest\n\`\`\`" \
            target/release/${{ env.APPLICATION_NAME }} \
            sha256sum.txt \
            md5sum.txt
